### ISSUE TITLE
Need help running it!

### ISSUE THREAD

**Issue by sbm4034** [SheikhZayed/Offline-Browser-Android-App#1]
Can you help us on bringing back the service so that it ll work!

**Comment by ashif-ismail** [comment]
sure,
the app i built was for my final project at university.it was just a prototype which i took down the server right after the usage.

for the app to work properly,you need 4 things : 

1)the app itself(you can improve the code quality,since i wrote this code when i started with android)

2)PostMan(android app that forwards the incoming sms(Requests) to the backend server(initially i used telerivet for this,but stopped it due to price concern).Developed an app similar to telerivet named Postman which is available in my repo list

3)backend server,which i have developed using Java EE that implements Boilerplate extraction algorithm
which is hosted @ [App Engine] (www.offlinebrowser-web.appspot.com) this does the main work of converting webpages into plain text

4)a microservice written in node.js that acts between postman app and backend to send response back to the requested user.(also available in this repo)

for sending SMS's i have subscribed with Kapsystem's bangalore for transactional SMS.

**Comment by sbm4034** [comment]
Sir Can we call! if you hhave any time! because I cannot seem to understand how will i use these all four to run this app! I am getting a hold of it! but still I am a noobie! hope you ll help!

**Comment by ashif-ismail** [comment]
sure,explore the app source code to find my no#

**Comment by sbm4034** [comment]
Okay thanku

**Comment by ashif-ismail** [comment]
try to assemble yourself,will help u if u get stuck
